sudo: required
services:
  - docker

before_install:
  - docker build -f docker/development.Dockerfile -t douglira/docker-udemy-webapp .

script:
  - docker run -e CI=true douglira/docker-udemy-webapp npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "docker-udemy-webapp"
  env: "Dockerudemywebapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-702694290822"
  bucket_path: "docker-udemy-webapp"
  on:
    branch: main