version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/development.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ../:/app
  
  web-tests:
    build:
      context: ..
      dockerfile: docker/development.Dockerfile
    volumes:
      - /app/node_modules
      - ../:/app
    command: ["npm", "run", "test"]